services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    image: aquapump-backend:latest
    pull_policy: never
    container_name: aquapump-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
      - CORS_ORIGIN=http://localhost:8080,http://frontend:8080
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aquapump-network

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    image: aquapump-frontend:latest
    pull_policy: never
    container_name: aquapump-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - EXPO_PUBLIC_RORK_API_BASE_URL=http://localhost:8081
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aquapump-network

networks:
  aquapump-network:
    driver: bridge