version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: runner
    image: aquapump:latest
    container_name: aquapump-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - PORT=8081
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aquapump-network

networks:
  aquapump-network:
    driver: bridge