apiVersion: v1
kind: ConfigMap
metadata:
  name: aquapump-config
  labels:
    {{- include "aquapump.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
