apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aquapump-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/aquapump.git
    targetRevision: dev
    path: infra/helm/aquapump
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: dev-latest
  destination:
    server: https://kubernetes.default.svc
    namespace: aquapump-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
