apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aquapump
  namespace: argocd
spec:
  description: AquaPump Project
  sourceRepos:
    - 'https://github.com/your-org/aquapump.git'
  destinations:
    - namespace: 'aquapump-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 1h
      applications:
        - '*'
