name: CI - Build & Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials (static fallback)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: testrepo
          IMAGE_TAG: ${{ github.sha }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          echo "Building Docker image for branch: $BRANCH_NAME"
          docker build --build-arg BRANCH=$BRANCH_NAME -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f infra/Dockerfile .
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Output image URL
        run: echo "✅ Image pushed to: ${{ steps.login-ecr.outputs.registry }}/testrepo:${{ github.sha }}"

